package com.uae4arm2026.data

object UpstreamConfig {
	const val GENERATED_BY_HEADER = "; Generated by UAE4Arm Android UI"

	const val KEY_TOUCH_SETTINGS_VERSION = "amiberry.touch_settings_version"
	const val KEY_ANDROID_JOYPORT1 = "amiberry.android_joyport1"
	const val KEY_SHOW_ANDROID_KEYBOARD_BUTTON = "amiberry.show_android_keyboard_button"
	const val KEY_ONSCREEN_JOYSTICK = "onscreen_joystick"
	const val KEY_AMIBERRY_ONSCREEN_JOYSTICK = "amiberry.onscreen_joystick"
	const val KEY_ONSCREEN_CD32PAD = "onscreen_cd32pad"
	const val KEY_AMIBERRY_ONSCREEN_CD32PAD = "amiberry.onscreen_cd32pad"
	const val KEY_VIRTUAL_KEYBOARD_ENABLED = "vkbd_enabled"
	const val KEY_DEFAULT_OSK = "input.default_osk"

	const val TOUCH_SETTINGS_VERSION = "1"
}